# Generated by Django 4.1.7 on 2023-03-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencia',
            name='fecha_caducidad',
            field=models.DateField(),
        ),
    ]
