# Generated by Django 4.1.7 on 2023-03-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0004_remove_licencia_clientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licencia',
            old_name='costo_renovacion',
            new_name='valor_base',
        ),
        migrations.AddField(
            model_name='licencia',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='licencia',
            name='iva',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='licencia',
            name='valor_anual',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='licencia',
            name='valor_renovacion',
            field=models.IntegerField(default=25),
        ),
    ]
