# Generated by Django 4.1.7 on 2023-03-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0004_remove_licencia_clientes'),
        ('clientes', '0002_remove_cliente_licencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='licencias',
            field=models.ManyToManyField(to='licencias.licencia'),
        ),
    ]
