# Generated by Django 4.1.7 on 2023-03-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0004_remove_licencia_clientes'),
        ('clientes', '0003_cliente_licencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLienteLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('licencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licencias.licencia')),
            ],
        ),
    ]
