# Generated by Django 4.1.7 on 2023-03-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_clientelicencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='licencias',
        ),
    ]
